### PR TITLE
change all px to rem with font base 16

### LINKED ISSUE #3: Convert every px unit value to rems.
In the style.css file, convert every pixel unit value to rems for better accessibility.

### PR DESCRIPTION
**Pull request by risanlang**
I have change all px values to rem with font base 16 as it is the default font for most browser
Hope this helps. If there is any problem please tell me so i could learn by helping.
Thank You

### CODE REVIEW

**Review by Evavic44 — APPROVED** [review]
Thanks. LGTM 👍🏾

**Comment by risanlang** [comment]
Thank you @Evavic44 for letting me to be apart of your work.
p.s I am also a fan of The Walking Dead

**Comment by Evavic44** [comment]
> Thank you @Evavic44 for letting me to be apart of your work.
> p.s I am also a fan of The Walking Dead

Really!? That awesome. Maybe we could work on a more advanced project sometime. 😎

**Comment by risanlang** [comment]
Yes if you have a project I would be glad to contribute, as I am also
learning and I am a person who learns best by doing and getting my hands
dirty
Thank you

**Comment by Evavic44** [comment]
Working on an opensource project soon. Will let you know about it.

**Pull request merged**
